---
name: ci

'on':
  pull_request:
  push:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_NO_PROGRESS: 'true'
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
          python-version: 3.14.5
          version: 0.11.16
      - run: make install
      - run: make check
